name: Pioneer
version: "1.0.2"
slug: pioneer
description: Find interesting posts
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
options:
  openai_api_key: ""
  telegram_bot_token: ""
  telegram_chat_id: ""
  openai_model: "gpt-4o-mini"
  prompt: ""
  only_post_if_relevant: false
  subreddits:
    - "diyelectronics"
    - "homeassistant"
    - "maker"
    - "matterprotocol"
    - "homeautomation"
schema:
  openai_api_key: password
  telegram_bot_token: password
  telegram_chat_id: str
  openai_model: str
  prompt: str
  only_post_if_relevant: bool
  subreddits:
    - str
